apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Testerii-app
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: Testerii
  project: Testerii-project
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: deploy/resources
    repoURL: https://github.com/tanuudemo/Testerii.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
